/**
 * Table-of-contents helpers for blog posts.
 *
 * `extractToc` scans the post's Markdown for H2/H3 headings and produces a flat
 * list of { depth, text, id }. The `id` is generated by a stateful slugger so
 * duplicate headings get unique, stable anchors. The blog post page renders its
 * Markdown headings through a slugger built the same way, so the anchors in the
 * TOC line up exactly with the `id`s on the rendered headings.
 */

export type TocEntry = { depth: 2 | 3; text: string; id: string };

/** Lowercase, strip Markdown emphasis/links, collapse to a hyphenated slug. */
export function slugifyHeading(text: string): string {
  return text
    .trim()
    .toLowerCase()
    // strip inline code / emphasis markers
    .replace(/[`*_~]/g, "")
    // markdown links [label](url) -> label
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    // drop anything that isn't a word char, space, or hyphen
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Returns a stateful slugger: calling it with the same base text more than once
 * appends `-1`, `-2`, … so every heading gets a unique id. Instantiate one per
 * render pass; feed it headings in document order.
 */
export function createSlugger(): (text: string) => string {
  const seen = new Map<string, number>();
  return (text: string) => {
    const base = slugifyHeading(text) || "section";
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    return n === 0 ? base : `${base}-${n}`;
  };
}

/** Extract H2/H3 headings from Markdown, skipping fenced code blocks. */
export function extractToc(markdown: string): TocEntry[] {
  const slug = createSlugger();
  const entries: TocEntry[] = [];
  let inFence = false;

  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trimEnd();
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    const m = /^(#{2,3})\s+(.*)$/.exec(line);
    if (!m) continue;
    const depth = m[1].length as 2 | 3;
    // strip trailing "##" style closers and surrounding whitespace
    const text = m[2].replace(/\s+#+\s*$/, "").trim();
    if (!text) continue;
    entries.push({ depth, text, id: slug(text) });
  }

  return entries;
}
